export const PARTY_TYPE_ID = {
    AUTOMATED_AGENT: "AUTOMATED_AGENT",
    CORPORATION: "CORPORATION",
    FAMILY: "FAMILY",
    GOVERNMENT_AGENCY: "GOVERNMENT_AGENCY",
    INFORMAL_GROUP: "INFORMAL_GROUP",
    LEGAL_ORGANIZATION: "LEGAL_ORGANIZATION",
    PARTY_GROUP: "PARTY_GROUP",
    PERSON: "PERSON",
    TEAM: "TEAM"
};

export const STATUS_ID = {
    ACTIVE: "ACTIVE",
    DEACTIVE: "DEACTIVE"
}